#!/bin/bash

DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"

function con() {
    local -i bytes=$1
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes}B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(( (bytes + 1023)/1024 ))KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(( (bytes + 1048575)/1048576 ))MB"
    else
        echo "$(( (bytes + 1073741823)/1073741824 ))GB"
    fi
}

echo -n > /tmp/other.txt
data=( $(cat /etc/xray/config.json | grep '###' | cut -d ' ' -f 2 | sort | uniq) )

echo -e "${cyan} ─────────────────────────────────────────────────"
echo -e "  expired     | usage  |   quota  | limit ip | akun${NC}"
echo -e "${cyan} ─────────────────────────────────────────────────${NC}"

for akun in "${data[@]}"; do
    if [[ -z "$akun" ]]; then
        akun="tidakada"
    fi
    echo -n > /tmp/ipvmess.txt
    data2=( $(cat /var/log/xray/access.log | tail -n 500 | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq) )

    for ip in "${data2[@]}"; do
        jum=$(cat /var/log/xray/access.log | grep -w "$akun" | tail -n 500 | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | grep -w "$ip" | sort | uniq)
        if [[ "$jum" = "$ip" ]]; then
            echo "$jum" >> /tmp/ipvmess.txt
        else
            echo "$ip" >> /tmp/other.txt
        fi
        jum2=$(cat /tmp/ipvmess.txt)
        sed -i "/$jum2/d" /tmp/other.txt > /dev/null 2>&1
    done

    jum=$(cat /tmp/ipvmess.txt)
    if [[ -z "$jum" ]]; then
        echo > /dev/null
    else
        iplimit=$(cat /etc/kyt/limit/vmess/ip/${akun} 2>/dev/null)
        jum2=$(cat /tmp/ipvmess.txt | wc -l 2>/dev/null)
        byte=$(cat /etc/vmess/${akun} 2>/dev/null)
        lim=$(con ${byte} 2>/dev/null)
        wey=$(cat /etc/limit/vmess/${akun} 2>/dev/null)
        exp=$(grep -wE "^### $akun" "/etc/xray/config.json" | cut -d ' ' -f 3 | sort | uniq)
        gb=$(con ${wey} 2>/dev/null)
        lastlogin=$(cat /var/log/xray/access.log | grep -w "$akun" | tail -n 500 | cut -d " " -f 2 | tail -1 2>/dev/null)
        echo -e "${NC}"
        printf "%-10s %-10s %-10s %-20s\n" "  $exp   "     "$gb" "$lim" "$iplimit IP    $akun"
        rm -rf /tmp/ipvmess.txt
    fi
done

rm -rf /tmp/other.txt
echo ""
echo -e "${Bold}\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}${Bold}"
echo ""