#!/bin/bash
clear
RED='\033[0;31m'
NC='\e[0m'
gray="\e[1;30m"
Blue="\033[1;36m"
GREEN='\033[0;32m'
KIRI="\033[1;32m>\033[1;33m>\033[1;31m>\033[1;31m"
BGX="\033[42m"
UPDATE="https://raw.githubusercontent.com/abgcell/sc/main/"
#BOT="https://raw.githubusercontent.com/myridwan/src/ipuk/"
UDPCORE="https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1S3IE25v_fyUfCLslnujFBSBMNunDHDk2"
clear

echo -e "${KIRI}==============================${NC}"
echo -e "${KIRI}         Menu System          ${NC}"
echo -e "${KIRI}==============================${NC}"

echo -e "  ${KIRI}1. ${NC}${GREEN}RUNNING SERVICE${NC}"
echo -e "  ${KIRI}2. ${NC}${GREEN}INSTALL UDP${NC}"
echo -e "  ${KIRI}3. ${NC}${GREEN}Registrasi IP VPS${NC}"
echo -e "  ${KIRI}4. ${NC}${GREEN}Update Script${NC}"
echo -e "  ${KIRI}5. ${NC}${GREEN}RESTART SERVICE${NC}"
echo -e "  ${KIRI}6. ${NC}${GREEN}CHANGE BANNER${NC}"
echo -e "  ${KIRI}7. ${NC}${GREEN}CHANGE DOMAIN${NC}"
echo -e "  ${KIRI}8. ${NC}${GREEN}Fix Missing Pointing Domain${NC}"
echo -e "  ${KIRI}9. ${NC}${GREEN}CLEAR LOGS${NC}"
echo -e "  ${KIRI}10. ${NC}${GREEN}CLEAR CACHE${NC}"
echo -e "  ${KIRI}11. ${NC}${GREEN}DELL ALL EXP${NC}"
echo -e "  ${KIRI}12. ${NC}${GREEN}Add Bot Notifikasi${NC}"
echo -e "  ${KIRI}13. ${NC}${GREEN}Monitor${NC}"
echo -e "  ${KIRI}14. ${NC}${GREEN}Install DNS Nonton${NC}"
echo -e "  ${KIRI}15. ${NC}${GREEN}Install Panel${NC}"
echo -e "  ${KIRI}16. ${NC}${GREEN}SPEEDTEST${NC}"
echo -e "  ${KIRI}17. ${NC}${GREEN}AutoReboot${NC}"
echo -e "  ${KIRI}18. ${NC}${GREEN}INFO PORT${NC}"
echo -e "  ${KIRI}19. ${NC}${GREEN}ON OFF NOTIF SC EXPIRED${NC}"
echo -e "  ${KIRI}0. ${NC}${GREEN}Back To Menu${NC}"
echo -e ""

read -p "Select From Options [1-18 or 0 to back to menu]: " menu

case $menu in
1)
    clear
    run
    ;;
2)
    clear
    udp
    ;;
3)
    clear
    add-ip
    ;;
4)
    clear
    wget https://raw.githubusercontent.com/BurhanLovers/vip/main/update.sh && chmod +x update.sh && ./update.sh
    ;;
5)
    clear
    reset
    ;;
6)
    clear
    nano /etc/kyt.txt
    ;;
7)
    clear
    addhost
    ;;
8)
    clear
    fixcert
    ;;
9)
    clear
    clearlog
    ;;
10)
    clear
    clearcache
    ;;
11)
    clear
    xp
    ;;
12)
    clear
    bot
    ;;
13)
    clear
    gotop
    ;;
14)
    clear
    wget https://raw.githubusercontent.com/Jengkolonline/nonton/main/nf.sh && chmod +x nf.sh && ./nf.sh
    ;;
15)
    clear
    m-panel
    ;;
16)
    clear
    speedtest
    ;;
17)
    clear
    autoreboot
    ;;
18)
    clear
    prot
    ;;
19)
    clear
    exp-onoff
    ;;    
0)
    clear
    menu
    ;;
*)
    clear
    menu
    ;;
esac